name: solidart_melos
publish_to: none

environment:
  sdk: ^3.6.0
dev_dependencies:
  melos: ^3.4.0
workspace:
  - packages/flutter_solidart
  - packages/solidart
  - packages/solidart_devtools_extension
  - packages/solidart_lint
